local:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
  vars:
    ansible_connection: local

lxd_containers:
  children:
    gr01:
      hosts:
        proj: 
  vars:
    ansible_connection: lxd