apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
type: Opaque
data:
  mariadb-root-password: c2VjcmV0 #echo -n 'secret'|base64
  MYSQL_DATABASE: bmV4dGNsb3Vk #echo -n 'nextcloud'|base64
  MYSQL_USER: bmV4dGNsb3Vk #echo -n 'nextcloud'|base64
  MYSQL_PASSWORD: bmV4dGNsb3Vk #echo -n 'nextcloud'|base64