apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  labels:
    app: nextcloud
type: Opaque
data:
  nextcloud-username: "YWRtaW4="
  nextcloud-password: "Y2hhbmdlbWU="
  nextcloud-token: "clJ6R2RKSXRhbg=="