---
kind: Service 
apiVersion: v1 
metadata:
  name: nginx
  labels:
    app: nginx
    layer: frontend    
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    layer: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /var/www/html/
              name: contents
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
            - mountPath: /usr/local/nginx/conf/
              name: certs
      volumes:
        - name: contents
          hostPath:
            path: /srv/content
            type: Directory
        - name: nginx-config
          hostPath:
            path: /srv/nginx.conf
            type: File
        - name: certs
          hostPath:
            path: /srv/certs
            type: Directory