---
kind: Service 
apiVersion: v1 
metadata:
  name: phpfpm
  labels:
    app: phpfpm
    layer: backend
spec:
  type: ClusterIP
  selector:
    app: phpfpm
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm
  labels:
    app: phpfpm
    layer: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpfpm
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      containers:
        - name: phpfpm
          image: php:fpm-alpine
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/html/
              name: contents
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "docker-php-ext-install pdo pdo_mysql mysqli && docker-php-ext-enable mysqli pdo pdo_mysql"]
                #exécuter -> docker-php-ext-install pdo pdo_mysql mysqli && docker-php-ext-enable mysqli pdo pdo_mysql
      volumes:
        - name: contents
          hostPath:
            path: /srv/content
            type: Directory