applications:
  - name: cluster-config
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/G6Maker/M2S1-Projet-Admin-et-Proto-Reseau.git
      targetRevision: HEAD
      path: Terraform/argocd/manifests
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: true
        selfHeal: true