applications:
  - name: cluster-config
    namespace: argocd
    project: default
    destination:
      name: ''
      namespace: argocd
      server: 'https://kubernetes.default.svc'
    source:
      path: Terraform/argocd/manifests
      repoURL: 'https://github.com/G6Maker/M2S1-Projet-Admin-et-Proto-Reseau.git'
      targetRevision: main
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
      